import PDFDocument from 'pdfkit';

export const generatePDF = (certificate) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const { extractedFields: f, aiAnalysis: ai, finalScore, verdict, createdAt } = certificate;

      // ── Header ──────────────────────────────────────
      doc.fontSize(20).font('Helvetica-Bold')
         .text('Certificate Verification Report', { align: 'center' });
      doc.moveDown(0.5);

      doc.fontSize(10).font('Helvetica')
         .fillColor('#666')
         .text(`Report ID: VR-${String(certificate._id).slice(-8).toUpperCase()}`, { align: 'center' })
         .text(`Verified on: ${new Date(createdAt).toLocaleDateString('en-IN')}`, { align: 'center' });

      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#ddd');
      doc.moveDown(1);

      // ── Verdict Banner ───────────────────────────────
      const verdictColor = verdict === 'Genuine' ? '#10b981' : verdict === 'Fake' ? '#ef4444' : '#f59e0b';
      const verdictBg    = verdict === 'Genuine' ? '#d1fae5' : verdict === 'Fake' ? '#fee2e2' : '#fef3c7';

      doc.rect(50, doc.y, 495, 50).fill(verdictBg);
      doc.fillColor(verdictColor).fontSize(18).font('Helvetica-Bold')
         .text(`Verdict: ${verdict.toUpperCase()}`, 50, doc.y - 40, { align: 'center' });
      doc.fillColor('#333').fontSize(12).font('Helvetica')
         .text(`Risk Score: ${finalScore}/100`, { align: 'center' });

      doc.moveDown(2);

      // ── Extracted Fields ─────────────────────────────
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#333')
         .text('Extracted Certificate Fields');
      doc.moveDown(0.5);

      const fieldRows = [
        ['Student Name',    f.name        || 'Not found'],
        ['Roll Number',     f.rollNumber  || 'Not found'],
        ['Marks',           f.marks       || 'Not found'],
        ['Certificate ID',  f.certId      || 'Not found'],
        ['University',      f.university  || 'Not found'],
        ['Year',            f.year        || 'Not found'],
        ['Degree',          f.degree      || 'Not found'],
      ];

      fieldRows.forEach(([label, value], i) => {
        const y = doc.y;
        if (i % 2 === 0) doc.rect(50, y, 495, 22).fill('#f8fafc');
        doc.fillColor('#555').fontSize(10).font('Helvetica-Bold').text(label, 60, y + 6);
        doc.fillColor('#111').font('Helvetica').text(value, 200, y + 6);
        doc.moveDown(0.8);
      });

      doc.moveDown(0.5);

      // ── AI Analysis Reasons ──────────────────────────
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#333')
         .text('AI Analysis Findings');
      doc.moveDown(0.5);

      if (ai.reasons && ai.reasons.length > 0) {
        ai.reasons.forEach(reason => {
          doc.fontSize(10).font('Helvetica').fillColor('#444')
             .text(`• ${reason}`, { indent: 10 });
        });
      } else {
        doc.fontSize(10).fillColor('#666').text('No suspicious patterns detected.');
      }

      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#666')
         .text(`AI Confidence: ${ai.confidence || 'N/A'}`);

      doc.moveDown(1);

      // ── Score Breakdown ──────────────────────────────
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#333')
         .text('Risk Score Breakdown');
      doc.moveDown(0.5);

      const bars = [
        { label: 'AI Analysis (40%)',    value: ai.score || 0 },
        { label: 'DB Match (30%)',       value: certificate.dbMatch ? 0 : 100 },
        { label: 'Completeness (30%)',   value: 100 - (certificate.breakdown?.completeness || 100) },
      ];

      bars.forEach(bar => {
        doc.fontSize(10).font('Helvetica').fillColor('#555').text(bar.label);
        const barW = Math.round((bar.value / 100) * 400);
        doc.rect(50, doc.y, 400, 10).fill('#e5e7eb');
        if (barW > 0) doc.rect(50, doc.y - 10, barW, 10).fill(verdictColor);
        doc.moveDown(0.8);
      });

      doc.moveDown(1);

      // ── DB Match Status ──────────────────────────────
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#333')
         .text('Database Match Result');
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica').fillColor('#444')
         .text(certificate.dbMatch
           ? '✓ Certificate record found in institution database'
           : '✗ No matching record found in institution database');

      doc.moveDown(2);

      // ── Footer ───────────────────────────────────────
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#ddd');
      doc.moveDown(0.5);
      doc.fontSize(9).fillColor('#999')
         .text('Generated by Academia Validator — AI-Powered Certificate Verification System', { align: 'center' })
         .text('Government of Jharkhand — Department of Higher and Technical Education', { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
